/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package calculator

const val sum = "+"
const val subtract = "-"
const val divide = "/"
const val multiply = "*"
const val percentage = "%"

class Calculator {

    fun operation(operation: String, n1: Float, n2: Float): Float {
        return when (operation) {
            sum -> (n1+n2)
            subtract -> (n1-n2)
            divide -> (n1/n2)
            multiply -> (n1*n2)
            percentage -> (n2 * (n1 /100))
            else -> throw Exception("Not allowed operation")
        }
    }
}

fun main(args: Array<String>) {
    val calculator = Calculator()
    var operation: String
    var first: Float
    var second: Float
    var result: Float

    println("---------------------------")
    println("This is a simple calculator")
    println("---------------------------")
    println("")

    while(true) {

        println("Enter the first number")
        first = readLine()?.toFloat() ?: 0F

        println("Enter one operand between the following: $sum,$subtract,$divide,$multiply,$percentage")
        operation = readLine().toString()

        println("Enter the second number")
        second = readLine()?.toFloat() ?: 0F

        result = calculator.operation(operation,first,second)
        println("$first $operation $second = $result")

        println("")
        println("Success, try again :)")
        println("")
    }
}
